# Generated by Django 2.2.7 on 2021-04-23 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='status_bar',
        ),
        migrations.AddField(
            model_name='data',
            name='settings_opacity_windows',
            field=models.FloatField(default=1.0, verbose_name='Прозрачность окон указателей'),
        ),
        migrations.AddField(
            model_name='data',
            name='settings_size_preview',
            field=models.IntegerField(default=150, verbose_name='Масштаб превью видеопотока'),
        ),
        migrations.AddField(
            model_name='data',
            name='settings_size_text',
            field=models.IntegerField(default=12, verbose_name='Масштаб текста списка датчиков'),
        ),
    ]
