# Generated by Django 2.2.7 on 2021-06-10 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='position_sidepanel_vs',
            field=models.IntegerField(default=150, verbose_name='Положение сплиттера боковой панели с видеопотоками '),
        ),
        migrations.AddField(
            model_name='data',
            name='show_sidepanel',
            field=models.BooleanField(default=True, verbose_name='Отображение боковой панели с объектами'),
        ),
    ]
